language: php

env:
  global:
    - PHPCS_IGNORE=build,lib
    - PHPCS_STANDARD=PSR2

php:
  - 5.6

before_script:
  - curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar

script:
  - php phpcs.phar --extensions=php --standard=$PHPCS_STANDARD --ignore=$PHPCS_IGNORE sgi/src -n
