version: "3"
services:
  web:
    image: airaup-php:latest
    build: ./sgi
    container_name: sgi_php
    volumes:
      - ./sgi/src:/var/www/html
    ports:
      - 8000:80
    environment:
      DB_HOST: mysql
      DB_USERNAME: c0310458_sgi
      DB_PASSWORD: Rotaract2016
      DB_DATABASE: c0310458_sgi
      SMTP_HOST: mailcatcher
      SMTP_PORT: 1025
      SMTP_FROM: sgi@airaup.org
      SMTP_FROMNAME: SGI AIRAUP
  mysql:
    image: mysql:5.6
    container_name: sgi_mysql
    volumes:
      - ./dumps:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_DATABASE: c0310458_sgi
      MYSQL_USER: c0310458_sgi
      MYSQL_PASSWORD: Rotaract2016
  adminer:
    image: adminer
    ports:
     - 8080:8080
  mailcatcher:
    image: schickling/mailcatcher
    ports:
    - 1080:1080
